language: scala
before_script: ./make_credentials.sh
script: sbt test

env:
  global:
    - secure: "WZMkwcbrRGzIfeHqljk0A+Praowhw+6A7/3KclMk2BpYQZQrg9cEMRE7KKioJc5uPniHybP0bpVfrwEn5we37itzKOG9DLrvkiN/SxBtC6/nRumoZtWdpgxIVoYdyblksWeeFi/S0ylvQrm2uk/1KQpY6xR2+ASMLdrpMvz2CE4="
    - secure: "lQEcCcMLy2E01rtebZGIZAkY+krhqjGr1t8TY+8a222LS+VUfOc8NXhfr2lmlseLy2WxJDJ9UDl7JtMJbgv5jwge1aXQFEFFovGnDpK60rjeF0fXjtHH74sGG2Veg3KevXV4CDoYIc+WyqHxjMdcREQg4N+gTCFUVlyTWBpRLFI="

# Publish to Sonatype if building master
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && sbt publish"